[config]
schemaVersion = "0.0.1"

[package]
namespace = "LeCloutPanda"
name = "Toggles" 
versionNumber = "1.4.0"
description = "Add toggles for features that really should have them."
websiteUrl = "https://github.com/lecloutpanda/Toggles"
containsNsfwContent = false

[package.dependencies] 
ResoniteModding-BepisLoader = "1.6.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "./LICENSE.md"
target = "/"


[[build.copy]]
source = "./Toggles/bin/Release/Toggles.dll"
target = "plugins/Toggles/"

[[build.copy]]
source = "./Toggles/bin/Release/Toggles.pdb"
target = "plugins/Toggles/"

[[build.copy]]
source = "./Toggles/Locale"
target = "plugins/Toggles/Locale"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = []